source "http://rubygems.org"

gem "eventmachine"
gem "unicorn"
gem "rainbows"
gem "puma"
gem "green"
gem "nio4r"
gem "algorithms"
gem "em-synchrony"
gem "m2r"

gem "em-http-request"

gem "thin-fun_embed", git: "git://github.com/funny-falcon/thin-fun_embed.git"
